---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goals-deployment
  labels:
    app: goals
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goals
  template:
    metadata:
      labels:
        app: goals
    spec:
      containers:
      - name: webserver
        image: codeboten/goals:2018
        ports:
        - containerPort: 80
